services:
  driver-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    cpus: 1
    cpu_count: 1
    cpu_percent: 5
    mem_reservation: 256MB
    mem_limit: 256MB
    environment:
      SPRING_PROFILES_ACTIVE: docker
    expose:
      - "8081"

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data

  mock-api:
    image: stoplight/prism:4
    command: mock -h 0.0.0.0 /tmp/api.yaml
    volumes:
      - ./src/main/resources/open-api-mocks/api.yaml:/tmp/api.yaml
    ports:
      - "4010:4010"
    environment:
      - PRISM_LOG_LEVEL=warn

  delay-api:
    image: ffnunes/delay-api:2.0.0
    ports:
      - "4020:4020"
    environment:
      PORT: 4020

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  mongodb-data:
    driver: local
