version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: local
  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
  zookeeper:
    image: confluentinc/cp-zookeeper:3.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:3.9.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1