version: '3.8'
services:
  driver-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_PROFILES_ACTIVE: docker
  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"