spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/driver-api-db
  cloud:
    circuitbreaker:
      resilience4j:
        disable-time-limiter: false
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            loggerLevel: BASIC
            readTimeout: 1000
          DelayApiFeignClient:
            url: http://delay-api:4020
            retryer: com.lab.driverapi.gateways.outputs.http.clients.delayApi.DelayApiClientRetryer
          MockApiFeignClient:
            url: http://mock-api:4010


management:
  endpoints:
    web:
      exposure.include: '*'
  endpoint:
    health.show-details: always
  health:
    circuitbreakers.enabled: true
    ratelimiters.enabled: true
  elastic:
    metrics:
      export:
        enabled: true



logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    io.github.resilience4j: DEBUG


driverapi:
  clients:
    delayApiClient:
      url: http://delay-api:4020


resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 4
      minimumNumberOfCalls: 4
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
  instances:
    MockApiFeignClient:
      baseConfig: default
    DelayApiFeignClient:
      baseConfig: default
    DelayApiClient:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxAttempts: 4
      waitDuration: 3000
      failAfterMaxAttempts: true
      retryExceptions:
        - java.net.SocketTimeoutException
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
  instances:
    DelayApiFeignClientRetry:
      baseConfig: default
    DelayApiFeignClient:
      baseConfig: default
    DelayApiClientdelayLong:
      baseConfig: default

resilience4j.rateLimiter:
  configs:
    default:
      limitForPeriod: 5
      timeoutDuration: 25
      limitRefreshPeriod: 1
  instances:
    MockApiFeignClient:
      baseConfig: default
    DelayApiFeignClient:
      baseConfig: default
    DelayApiClient:
      baseConfig: default
