spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/driver-api-db
  cloud:
    circuitbreaker:
      resilience4j:
        disable-time-limiter: true
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            loggerLevel: BASIC
            readTimeout: 1000
          DelayApiFeignClient:
            url: http://localhost:4020
            retryer: com.lab.driverapi.gateways.outputs.http.clients.delayApi.DelayApiClientRetryer
          MockApiFeignClient:
            url: http://localhost:4010

management:
  endpoints:
    web:
      exposure.include: '*'
  endpoint:
    health.show-details: always
  health:
    circuitbreakers.enabled: true
    ratelimiters.enabled: true

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    io.github.resilience4j: DEBUG

resilience4j.circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 4
        minimumNumberOfCalls: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3 # Abre o circuito se 2 falharem (2/3 failure rate 66%)
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      MockApiFeignClient:
        baseConfig: default
      DelayApiFeignClient:
        baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxAttempts: 4
      waitDuration: 3000
      failAfterMaxAttempts: true
      retryExceptions:
        - java.net.SocketTimeoutException
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
  instances:
    DelayApiFeignClientRetry:
      baseConfig: default
    DelayApiFeignClient:
      baseConfig: default
    DelayApiClientdelayLong:
      baseConfig: default

resilience4j.timelimiter:
    timeLimiterAspectOrder: 1
    configs:
      default:
        timeoutDuration: 3000           # Limite máximo de tempo de resposta da requisoção
        cancelRunningFuture: true
    instances:
      MockApiFeignClient:
        baseConfig: default
      DelayApiFeignClient:
        baseConfig: default


