spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/driver-api-db
  cloud:
    circuitbreaker:
      resilience4j:
        disable-time-limiter: false
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            loggerLevel: BASIC
            readTimeout: 1000
          DelayApiFeignClient:
            url: http://localhost:4020
            retryer: com.lab.driverapi.gateways.outputs.http.clients.delayApi.DelayApiClientRetryer
          MockApiFeignClient:
            url: http://localhost:4010

server:
  undertow:
    threads:
      io: 4
      worker: 20

management:
  endpoints:
    web:
      exposure.include: '*'
  endpoint:
    health.show-details: always
  health:
    circuitbreakers.enabled: true
    ratelimiters.enabled: true

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    io.github.resilience4j: DEBUG

elastic:
  apm:
    service_name: driver-api
    server_url: http://localhost:8200
    application_packages: com.lab.driverapi
    environment: local

driverapi:
  clients:
    delayApiClient:
      url: http://localhost:4020


resilience4j.circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 4
        minimumNumberOfCalls: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      MockApiFeignClient:
        baseConfig: default
      DelayApiFeignClient:
        baseConfig: default
      DelayApiClient:
        baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxAttempts: 4
      waitDuration: 3000
      failAfterMaxAttempts: true
      retryExceptions:
        - java.net.SocketTimeoutException
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
  instances:
    DelayApiFeignClientRetry:
      baseConfig: default
    DelayApiFeignClient:
      baseConfig: default
    DelayApiClientdelayLong:
      baseConfig: default

resilience4j.rateLimiter:
    configs:
      default:
        limitRefreshPeriod: 1
        limitForPeriod: 5
        timeoutDuration: 15
    instances:
      MockApiFeignClient:
        baseConfig: default
      DelayApiFeignClient:
        baseConfig: default
      DelayApiClient:
        baseConfig: default


