openapi: 3.0.0
info:
  title: Mock API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Retorna uma mensagem simples
      responses:
        '200':
          description: Mensagem de boas-vindas
          content:
            application/json:
              example:
                message: "Hello world!"
  /hello-error:
    get:
      summary: Retorna uma mensagem simples
      responses:
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                message: "Hello world!"